# Generated by Django 4.1.1 on 2022-09-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='numero',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
