# Generated by Django 4.1 on 2022-09-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='item',
            name='numero',
        ),
        migrations.AddField(
            model_name='item',
            name='album',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
