# Generated by Django 4.1 on 2022-09-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
