# Generated by Django 4.1.1 on 2022-09-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_profile_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto_perfil',
            field=models.FileField(blank=True, null=True, upload_to='static'),
        ),
    ]
