# Generated by Django 4.1 on 2022-09-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsprivados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprivado',
            name='nome',
        ),
        migrations.AddField(
            model_name='itemprivado',
            name='album',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='itemprivado',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='itemprivado',
            name='explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemprivado',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
